//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web;
namespace Cost_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense_form
    {
        public int ID { get; set; }
        public string formID { get; set; }
        public string formName { get; set; }
        public string formNumber { get; set; }
        public string RequireNumber { get; set; }
        public double circleID { get; set; }
        public string description { get; set; }
        public string nation { get; set; }
        public string exp_date { get; set; }
        public string location { get; set; }
        public string userID { get; set; }
        public string userName { get; set; }
        public string exp_type { get; set; }
        public string exp_attr { get; set; }
        public string currency { get; set; }
        public double QTY { get; set; }
        public string price { get; set; }
        public double amount { get; set; }
        public string tax { get; set; }
        public string invoice { get; set; }
        public string projectCode { get; set; }
        public string lmtime { get; set; }
        public string lmuser { get; set; }
        public System.DateTime signtime { get; set; }
        public string signuser { get; set; }
        public System.DateTime closetime { get; set; }
        public string closeuser { get; set; }
        public string note { get; set; }
        public string DocumentsNumber { get; set; }
        public string picture { get; set; }
        public string picture1 { get; set; }
        public string picture2 { get; set; }
        public bool SignStatus { get; set; }
        public string form_id { get; set; }
        public string channel_id { get; set; }
        public string create_time { get; set; }
        public HttpPostedFileBase ItemImage0 { get; set; }
        public HttpPostedFileBase ItemImage1 { get; set; }
        public HttpPostedFileBase ItemImage2 { get; set; }
    }
}
